name: 'CI/CD Observability'
description: 'Collect CI/CD metrics and traces following OpenTelemetry semantic conventions'
author: 'turytsia'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  
  webhook-url:
    description: 'Webhook URL to send observability data'
    required: false
  
  webhook-secret:
    description: 'Secret for signing webhook payloads (HMAC-SHA256)'
    required: false
  
  collect-metrics:
    description: 'Enable metrics collection'
    required: false
    default: 'true'
  
  collect-traces:
    description: 'Enable traces collection'
    required: false
    default: 'true'

  # SolarWinds / OTLP Configuration
  swo-service-key:
    description: 'SolarWinds APM Service Key (SW_APM_SERVICE_KEY format: token:service-name)'
    required: false

  swo-collector:
    description: 'SolarWinds APM Collector endpoint (e.g., apm.collector.na-01.st-ssp.solarwinds.com)'
    required: false

outputs:
  metrics-json:
    description: 'Collected metrics in JSON format'
    value: ${{ steps.observability.outputs.metrics-json }}
  
  traces-json:
    description: 'Collected traces in JSON format'
    value: ${{ steps.observability.outputs.traces-json }}
  
  summary:
    description: 'Brief summary of the observability data'
    value: ${{ steps.observability.outputs.summary }}

runs:
  using: 'composite'
  steps:
    - name: Setup SolarWinds APM
      if: ${{ inputs.swo-service-key != '' }}
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "Installing solarwinds-apm for telemetry export..."
        npm install --no-save solarwinds-apm @opentelemetry/api@^1.9.0 2>/dev/null || true

    - name: Run CI/CD Observability
      id: observability
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_WEBHOOK-URL: ${{ inputs.webhook-url }}
        INPUT_WEBHOOK-SECRET: ${{ inputs.webhook-secret }}
        INPUT_COLLECT-METRICS: ${{ inputs.collect-metrics }}
        INPUT_COLLECT-TRACES: ${{ inputs.collect-traces }}
        INPUT_SWO-SERVICE-KEY: ${{ inputs.swo-service-key }}
        INPUT_SWO-COLLECTOR: ${{ inputs.swo-collector }}
        # SolarWinds APM environment variables
        SW_APM_SERVICE_KEY: ${{ inputs.swo-service-key }}
        SW_APM_COLLECTOR: ${{ inputs.swo-collector }}
        SW_APM_LOG_LEVEL: info
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        if [ -n "$SW_APM_SERVICE_KEY" ]; then
          echo "Running with SolarWinds APM instrumentation..."
          node --import solarwinds-apm dist/index.js
        else
          node dist/index.js
        fi
