name: 'CI/CD Observability'
description: 'Collect CI/CD metrics and traces following OpenTelemetry semantic conventions'
author: 'turytsia'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  
  webhook-url:
    description: 'Webhook URL to send observability data'
    required: false
  
  webhook-secret:
    description: 'Secret for signing webhook payloads (HMAC-SHA256)'
    required: false
  
  collect-metrics:
    description: 'Enable metrics collection'
    required: false
    default: 'true'
  
  collect-traces:
    description: 'Enable traces collection'
    required: false
    default: 'true'

  # SolarWinds / OTLP Configuration
  swo-service-key:
    description: 'SolarWinds APM Service Key (SW_APM_SERVICE_KEY format: token:service-name)'
    required: false

  swo-collector:
    description: 'SolarWinds APM Collector endpoint (e.g., apm.collector.na-01.st-ssp.solarwinds.com)'
    required: false
    default: 'apm.collector.na-01.st-ssp.solarwinds.com'

outputs:
  metrics-json:
    description: 'Collected metrics in JSON format'
    value: ${{ steps.run.outputs.metrics-json }}
  
  traces-json:
    description: 'Collected traces in JSON format'
    value: ${{ steps.run.outputs.traces-json }}
  
  summary:
    description: 'Brief summary of the observability data'
    value: ${{ steps.run.outputs.summary }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci --ignore-scripts 2>/dev/null || npm install --ignore-scripts

    - name: Run observability collection
      id: run
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        # Action inputs as env vars
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_WEBHOOK_URL: ${{ inputs.webhook-url }}
        INPUT_WEBHOOK_SECRET: ${{ inputs.webhook-secret }}
        INPUT_COLLECT_METRICS: ${{ inputs.collect-metrics }}
        INPUT_COLLECT_TRACES: ${{ inputs.collect-traces }}
        INPUT_SWO_SERVICE_KEY: ${{ inputs.swo-service-key }}
        INPUT_SWO_COLLECTOR: ${{ inputs.swo-collector }}
        # SolarWinds APM environment variables
        SW_APM_SERVICE_KEY: ${{ inputs.swo-service-key }}
        SW_APM_COLLECTOR: ${{ inputs.swo-collector }}
      run: |
        if [ -n "$SW_APM_SERVICE_KEY" ]; then
          echo "Running with SolarWinds APM instrumentation..."
          node --import solarwinds-apm dist/index.js
        else
          echo "Running without SolarWinds APM..."
          node dist/index.js
        fi
