name: 'CI/CD Observability'
description: 'Collect CI/CD metrics and traces following OpenTelemetry semantic conventions'
author: 'turytsia'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  
  webhook-url:
    description: 'Webhook URL to send observability data'
    required: false
  
  webhook-secret:
    description: 'Secret for signing webhook payloads (HMAC-SHA256)'
    required: false
  
  collect-metrics:
    description: 'Enable metrics collection'
    required: false
    default: 'true'
  
  collect-traces:
    description: 'Enable traces collection'
    required: false
    default: 'true'

  # SolarWinds / OTLP Configuration
  swo-service-key:
    description: 'SolarWinds APM Service Key (SW_APM_SERVICE_KEY format: token:service-name)'
    required: false

  swo-collector:
    description: 'SolarWinds APM Collector endpoint (e.g., apm.collector.na-01.st-ssp.solarwinds.com)'
    required: false

outputs:
  metrics-json:
    description: 'Collected metrics in JSON format'
  
  traces-json:
    description: 'Collected traces in JSON format'
  
  summary:
    description: 'Brief summary of the observability data'

runs:
  using: 'node20'
  main: 'dist/index.js'
